# Generated by Django 2.0.1 on 2018-02-07 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.CharField(max_length=80, unique=True)),
                ('resource_url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_uuid', models.CharField(max_length=80, unique=True)),
                ('job_category', models.CharField(max_length=80)),
                ('job_task_time_difference', models.DurationField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(choices=[('AC', 'Access Control'), ('AL', 'Alarm'), ('CT', 'CCTV'), ('DE', 'Door Entry'), ('EL', 'Emergency Lights'), ('FA', 'Fire Alarm'), ('FE', 'Fire Extinguisher'), ('KE', 'Key Holding'), ('NC', 'Nurse Call'), ('R', 'Refuge')], max_length=2)),
                ('contracted', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('contract_date', models.DateField()),
                ('install_date', models.DateField()),
                ('maintenance_interval', models.CharField(choices=[('M', 'Monthly'), ('Y', 'Yearly'), ('H', 'Half yearly'), ('T', 'Tri-yearly'), ('Q', 'Quarterly')], max_length=1)),
                ('monitoring_type', models.CharField(choices=[('A', 'Audible'), ('M', 'Monitored')], max_length=1)),
                ('monitoring_acct_num', models.CharField(max_length=80)),
                ('maintenance_form_setup', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('urn_intruder', models.CharField(max_length=80)),
                ('urn_pa', models.CharField(max_length=80)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_uuid', models.CharField(max_length=80, unique=True)),
                ('related_object_uuid', models.CharField(max_length=80)),
                ('due_date', models.DateField()),
                ('completed_timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Job')),
            ],
        ),
    ]
