# Generated by Django 2.0.1 on 2018-02-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_task_time_difference',
            field=models.DurationField(null=True),
        ),
    ]
