# Generated by Django 2.0.1 on 2018-02-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20180207_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
