# Generated by Django 2.0.1 on 2018-02-08 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20180208_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_timestamp',
        ),
        migrations.AddField(
            model_name='task',
            name='completed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
