# Generated by Django 2.0.1 on 2018-02-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20180208_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='job_task_time_difference',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
