# Generated by Django 2.0.1 on 2018-02-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20180209_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='contract_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='contracted',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='install_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='maintenance_form_setup',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='maintenance_interval',
            field=models.CharField(blank=True, choices=[('M', 'Monthly'), ('Y', 'Yearly'), ('H', 'Half yearly'), ('T', 'Tri-yearly'), ('Q', 'Quarterly')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='monitoring_acct_num',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='monitoring_type',
            field=models.CharField(blank=True, choices=[('A', 'Audible'), ('M', 'Monitored')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='system_type',
            field=models.CharField(blank=True, choices=[('AC', 'Access Control'), ('AL', 'Alarm'), ('CT', 'CCTV'), ('DE', 'Door Entry'), ('EL', 'Emergency Lights'), ('FA', 'Fire Alarm'), ('FE', 'Fire Extinguisher'), ('KE', 'Key Holding'), ('NC', 'Nurse Call'), ('R', 'Refuge')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='urn_intruder',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='urn_pa',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
