# Generated by Django 2.0.1 on 2018-05-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20180218_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='system_type',
            field=models.CharField(blank=True, choices=[('AC', 'Access Control'), ('AL', 'Alarm'), ('CT', 'CCTV'), ('DE', 'Door Entry'), ('EL', 'Emergency Lights'), ('FA', 'Fire Alarm'), ('FE', 'Fire Extinguisher'), ('KE', 'Key Holding'), ('NC', 'Nurse Call'), ('R', 'Refuge'), ('M', 'Miscellaneous')], max_length=2, null=True),
        ),
    ]
