# Generated by Django 2.0.1 on 2018-05-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20180502_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='monitoring_type',
            field=models.CharField(blank=True, choices=[('A', 'Audible'), ('M', 'Monitored'), ('D', 'Dualcom'), ('DI', 'Digi'), ('DIP', 'Digi-Plus'), ('DIA', 'Digi-Air'), ('RC', 'Redcare Classic'), ('RS', 'Redcare SEcure'), ('N', 'None')], max_length=3, null=True),
        ),
    ]
