# Generated by Django 2.0.1 on 2018-05-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20180502_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='system_monitoring_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='system',
            name='system_price_ex_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
