# Generated by Django 2.0.1 on 2018-05-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20180505_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='maintenance_form_setup',
        ),
    ]
