# Generated by Django 2.0.1 on 2018-05-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_remove_system_maintenance_form_setup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['client']},
        ),
    ]
